version: 2
updates:
  - package-ecosystem: 'pip'
    directory: '/backend'
    schedule:
    interval: 'monthly'
    open-pull-requests-limit: 0
    groups:
      python:
        applies-to: security-updates
    versioning-strategy: 'increase'
